"""add end and start date for tasks

Revision ID: 273ffaff3d2e
Revises: 92ca5f344bbf
Create Date: 2024-09-05 14:39:52.741962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273ffaff3d2e'
down_revision = '92ca5f344bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
