"""remove timezone from user

Revision ID: 38ba6a7a3aa9
Revises: 13bd88504a91
Create Date: 2024-09-06 05:23:19.276784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ba6a7a3aa9'
down_revision = '13bd88504a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
